config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :meetings do
    resources :user_meetings, only: [:create]
  end
  resources :boardgames, only: [:index, :show]
  resources :user_meetings, only: [:destroy]
  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  get 'my_meetings', to: "meetings#my_meetings"
  get 'calendar', to: 'meetings#calendar'
  resources :user_boardgames, only: [:new, :create, :index, :destroy]
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :boardgame
  belongs_to :chatroom
  has_many :user_meetings, dependent: :destroy
  has_many :users, through: :user_meetings

  validates :user_id, :address, :name, :boardgame_id, :start_date, :start_time,
            :players_wanted, :user_is_owner, presence: true

  validate :start_date_cannot_be_in_the_past, on: :create
  validate :meeting_cannot_have_more_players_than_game_allows, on: :create
  validate :cannot_create_meeting_if_busy_at_that_time, on: :create

  after_create :create_user_meeting

  include PgSearch::Model
  pg_search_scope :search_by_name_and_address_and_host,
                  against: %i[address name start_date],
                  associated_against: {
                    boardgame: [:name],
                    user: [:email]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?

  scope :not_full, -> { where('players_total < players_wanted') }

  def meeting_cannot_have_more_players_than_game_allows
    return unless players_wanted > boardgame.max_players

    errors.add(:players_wanted, "can't have more players than the game allows")
  end

  def full?
    players_wanted == users.count
  end

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "can't be in the past") if start_date < Date.today
  end

  def cannot_create_meeting_if_busy_at_that_time
    user_meetings = user.meetings.where(start_date: start_date, start_time: start_time)
    if user_meetings.any?
      record.errors.add(
        :meeting,
        "You already have a meeting at that time"
      )
    end
  end

  private

  def create_user_meeting
    UserMeeting.create!(user: user, meeting: self)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [ :show, :edit, :update, :destroy ]
  skip_before_action :authenticate_user!, only: [ :index ]


  def index
    if current_user.blank?
      redirect_to root_path
      skip_policy_scope
      return
    end

    if params[:query].present?
      @meetings = policy_scope(Meeting.search_by_name_and_address_and_host(params[:query])).near(current_user.profile.city, 8000)
    else
      nearby_meetings = policy_scope(Meeting).order(start_date: :asc).order(start_time: :asc).near(current_user.profile.city)
      other_meetings = policy_scope(Meeting).near(current_user.profile.city, 5000) - nearby_meetings
      @meetings = nearby_meetings + other_meetings
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'meetings/list', locals: { meetings: @meetings }, formats: [:html] }
    end
  end

  def show
    @user = User.where(params[:user])

    @user_meeting = UserMeeting.where(meeting_id: @meeting.id).select do |user_meeting|
      user_meeting.user == current_user
    end

    @user_meeting = UserMeeting.new unless @user_meeting.present?

    @marker = [{
      lat: @meeting.latitude,
      lng: @meeting.longitude
    }]
  end

  def new
    @boardgame = Boardgame.find(params[:boardgame_id]) if params[:boardgame_id]

    @meeting = Meeting.new
    authorize @meeting
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user = current_user
    @meeting.chatroom = Chatroom.new
    authorize @meeting

    if @meeting.save!
      redirect_to meeting_path(@meeting), notice: 'meeting was successfully scheduled.' and return
    else
      render :new, notice: 'you already have a meeting at that time'
    end
  end

  def edit; end

  def update
    if @meeting.update(meeting_params)
      redirect_to meeting_path(@meeting), notice: 'meeting was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @meeting.destroy
    redirect_to my_meetings_path, notice: "#{@meeting.name} was successfully canceled."
  end

  def my_meetings
    @meetings = policy_scope(current_user.owned_meetings)
    authorize @meetings
  end

  def calendar
    @meetings = policy_scope(current_user.meetings)
    authorize @meetings
  end

  private

  def meeting_params
    params.require(:meeting).permit(
      :name, :latitude, :longitude, :boardgame_id.name, :start_date, :start_time, :players_wanted, :user_is_owner, :address, :description
    )
  end

  def set_meeting
    @meeting = Meeting.find(params[:id])
    authorize @meeting
  end

end

app/views/meetings/_form.html.erb
<%= simple_form_for(meeting) do |f| %>
  <%= f.input :name, label: "boardgame meeting title", input_html: { class: "form-radius mb-0" }  %>
  <div data-controller='min-max-players'>
    <%= f.association :boardgame,
                      # selected: boardgame_id,
                      label: "boardgame",
                      input_html: { class: "form-radius", data: { min_max_players_target: 'name', action: "change->min-max-players#updatePlayers"} }
      %>

    <div data-controller='flatpickr'>
      <%= f.input :start_date, label: "date", as: :string, input_html: {class:'datepickr form-radius mb-0'}%>
      <%= f.input :start_time, label: "time", as: :string, input_html: {class:'timepickr form-radius mb-0'} %>
    </div>

    <div data-controller='geocoder' data-geocoder-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" class="mb-3">
      <%= f.input :latitude, as: :hidden, input_html: { data: { geocoder_target: 'latt' } } %>
      <%= f.input :longitude, as: :hidden, input_html: { data: { geocoder_target: 'longt' } } %>

      <%= f.input :address,
                label: "address",
                label_html: { class: 'mb-0'},
                input_html: {
                  data: { geocoder_target: "address" },
                  class: "d-none"
                }
      %>
    </div>
    <div class="players_wanted">
      <%= f.input :players_wanted,
                  label: "total players",
                  collection: ['Choose a game first...'],
                  input_html: { data: { min_max_players_target: 'total'}, class: "form-radius" },
                  include_blank: false,
                  include_hidden: false
        %>
      <i class="fa-solid fa-caret-down"></i>
    </div>

  </div>
  <div class="d-flex justify-content-center">
    <%= f.input :user_is_owner, label: "i own the game"%>
  </div>
  <%= f.input :description, label: "comments", input_html: { class: "form-radius" } %>
  <div class="btn-container">
    <% if meeting.new_record? %>
      <div class="form-actions a_btn">
        <%= f.button :submit, "create", class: "a_btn" %>
      </div>
    <% else %>
      <div class="form-actions a_btn">
        <%= f.button :submit, "update", class: "a_btn" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/meetings/_list.html.erb
<div data-search-meetings-target="list">
  <% meetings.each do |meeting| %>
    <%= link_to meeting_path(meeting) do %>
      <div class="card-product <%= "darkened-card" if meeting.full? %>" >
        <%= cl_image_tag meeting.boardgame.photo.key, width: 96 %>
        <div class="card-product-infos d-flex flex-column justify-content-between w-100 ellipsis">
          <div class="meeting-title ellipsis">
            <h2><%= meeting.name %></h2>
          </div>
          <div class="address ellipsis">
            <p><i class="fa-solid fa-location-dot"></i> <%= meeting.address %></p>
          </div>
          <div class="date-and-time ellipsis">
            <p><i class="fa-solid fa-calendar"></i> <%= meeting.start_date.strftime('%a %d %b') %> <%= meeting.start_time.strftime("%k:%M")%></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<%# <%= h truncate(meeting.user.email, :length => 50) %>
<%# style="padding: 3px" %>

app/views/meetings/calendar.html.erb
<div class="px-4">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <h1>calendar</h1>

        <!-- .group_by { |meeting| meeting.date } -->

        <% @meetings.order(:start_date, :start_time).group_by(&:start_date).each do |date, meetings| %>

          <div class='calendar-card'>
            <p><%= date.strftime('%A, %d %B %Y')%></p>
              <ul>
                <% meetings.each do |meeting| %>
                  <li><i class="fa-solid fa-calendar calendar_btn calendar-icon"></i>  <%= meeting.start_time.strftime("%H:%M") %> <%= link_to meeting.name, meeting_path(meeting) %></li>
                <% end %>
              </ul>
          </div>

        <% end %>
    </div>
  </div>
</div>

<%# class="fa-solid fa-calendar calendar_btn" %>

app/views/meetings/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-4 col-sm-offset-4">
      <div class="form-login-signup">
        <h1>edit meeting</h1>
        <%= render 'form', meeting: @meeting %>
      </div>
    </div>
  </div>
</div>

app/views/meetings/index.html.erb
<% # meeting should be a card with info %>
<div class="px-4" data-controller="search-meetings">

  <div class="search-bar">
  <i class="fas fa-search fs-6"></i>
    <%= form_with url: meetings_path, method: :get,
        html: { class: '', data: { search_meetings_target: 'form' } } do %>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control ps-5 form-radius",
          placeholder: "search boardgame meetings",
          value: params[:query],
          data: {
            search_meetings_target: 'input',
            action: 'keyup->search-meetings#update'
            }
      %>
    <% end %>
    <%# <%= submit_tag "Search", class: "" %>
  </div>

  <%= link_to(@meetings_path) do %>
    <h1>game meetings</h1>
  <% end %>

  <%= render 'list', meetings: @meetings %>
</div>

app/views/meetings/my_meetings.html.erb
<div class="px-4">
  <h1>my meetings</h1>
  <div data-search-meetings-target="list">
    <% @meetings.each do |meeting| %>
        <%= link_to meeting_path(meeting) do %>
          <div class="card-product">
            <%= cl_image_tag meeting.boardgame.photo.key, width: 96 %>
            <div class="card-product-infos d-flex flex-column justify-content-between w-100 ellipsis">
              <div class="meeting-title ellipsis">
                <h2><%= meeting.name %></h2>
              </div>
              <div class="address ellipsis">
                <p><i class="fa-solid fa-location-dot"></i> <%= meeting.address %></p>
              </div>
              <div class="date-and-time ellipsis">
                <p><i class="fa-solid fa-calendar"></i> <%= meeting.start_date.strftime('%a %d %b') %> <%= meeting.start_time.strftime("%k:%M")%></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <div class="d-flex justify-content-center pt-4 pb-3">
        <%= link_to 'back', :back, class:'b_btn material' %>
      </div>
  </div>
</div>

app/views/meetings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-4 col-sm-offset-4">
      <div class="form-login-signup">
        <h1>game meeting</h1>
        <%= render 'form', meeting: @meeting, boardgame_id: (@boardgame.id if @boardgame) %>
      </div>
    </div>
  </div>
</div>

app/views/meetings/show.html.erb
<div class="px-4">
  <h1 class="pb-3 d-flex justify-content-center text-center"><%=@meeting.name %></h1>
  <div class="px-4 text-center">
    <%= cl_image_tag @meeting.user.profile.photo.key, class:'avatar' %>
    <p><%= @meeting.user.profile.name %></p>
  </div>

    <div class="d-flex justify-content-center">
      <p><%= link_to(boardgame_path(@meeting.boardgame)) do %><%= @meeting.boardgame.name %></p>
    </div>
    <div class="text-center pb-4">
      <%= cl_image_tag @meeting.boardgame.photo.key, width: '75%', class: 'game-photo my-4'%>
    </div>
    <% end %>

    <div class="text-center px-3">
      <p><i class="fa fa-solid fa-calendar" style="color: #A380BD"></i> <%= @meeting.start_date.strftime('%A, %d %B %Y') %>, <%= @meeting.start_time.strftime("%H:%M")%></p>
      <p><i class="fa fa-solid fa-location-dot" style="color: #A380BD"></i> <%= @meeting.address %></p>
    </div>
    <div class="text-center mb-5">
    <% @meeting.users.count.times do %>
      <%= render 'shared/small_meeple'%>
    <% end %>
    <% (@meeting.players_wanted - @meeting.users.count).times do %>
      <%=render 'shared/small_gray_meeple' %>
    <% end %>
      <% if @meeting.full? %>
        <p style="color: #6e6d6d">(Meeting is full)</p>
      <% else %>
        <p style="color: #6e6d6d">(Waiting for <%= (@meeting.players_wanted - @meeting.users.count) %>/<%= @meeting.players_wanted %> players)</p>
      <% end %>
      <div class="text-center">
      <% @meeting.users.each do |user| %>
        <%= cl_image_tag user.profile.photo.key, class: 'avatar' %>
        <p>   <%= user.profile.name %></p>
      <% end %>
      </div>
    </div>
    <div style="width: 100%; height: 200px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @marker.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <div class="text-justify pt-3">
      <p style="color: #A380BD" class="mb-0">comments:</p>
      <p style="color: #6e6d6d; text-align: left" ><%= @meeting.description%></p>
    </div>
    <% unless @meeting.users.find_by(id: current_user.id).present? || @meeting.full? %>
      <div class="d-flex justify-content-center py-2">
        <%= simple_form_for [@meeting, @user_meeting] do |f| %>
          <%= f.submit "join", class: "a_btn" %>
        <% end %>
      </div>
    <% end %>
      <% if policy(@meeting).edit? %>
        <div class="d-flex justify-content-center py-2">
          <%= link_to 'edit', edit_meeting_path(@meeting), class:'b_btn material' %>
        </div>
      <% end %>
      <% if policy(@meeting).destroy? %>
        <div class="d-flex justify-content-center py-2">
          <%= link_to 'cancel meeting', meeting_path(@meeting), method: :delete, data: { confirm: 'Are you sure?' }, class: 'b_btn material' %>
        </div>
      <% end %>
      <% if @user_meeting.present? %>
        <% if policy(@user_meeting).destroy? && (@meeting.user != current_user) %>
          <div class="d-flex justify-content-center py-2">
            <%= link_to 'leave meeting', user_meeting_path(@user_meeting), method: :delete, data: { confirm: 'Are you sure?' }, class: 'b_btn material' %>
          </div>
        <% end %>
      <% end %>
      <% if policy(@meeting.chatroom).show? %>
        <div class="d-flex justify-content-center py-2">
          <%= link_to 'chat', chatroom_path(@meeting.chatroom), class:'a_btn' %>
        </div>
      <% end %>
    <div class="d-flex justify-content-center py-2">
      <%= link_to 'back', meetings_path, class:'b_btn material' %>
    </div>
  </div>
</div>