config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :meetings do
    resources :user_meetings, only: [:create]
  end
  resources :boardgames, only: [:index, :show]
  resources :user_meetings, only: [:destroy]
  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  get 'my_meetings', to: "meetings#my_meetings"
  get 'calendar', to: 'meetings#calendar'
  resources :user_boardgames, only: [:new, :create, :index, :destroy]
end

app/models/user_boardgame.rb
class UserBoardgame < ApplicationRecord
  belongs_to :user
  belongs_to :boardgame
end

app/controllers/user_boardgames_controller.rb
class UserBoardgamesController < ApplicationController

  def index
    @user_boardgames = policy_scope(UserBoardgame)
  end

  def new
    @user_boardgame = UserBoardgame.new
    authorize @user_boardgame
  end

  def create
    @user_boardgame = UserBoardgame.new(user_boardgame_params)
    @user_boardgame.user = current_user
    authorize @user_boardgame
    if @user_boardgame.save!
      redirect_to user_boardgames_path, notice: "#{@user_boardgame.boardgame.name} added to collection."
    else
      render :new
    end
  end

  def destroy
    @user_boardgame = UserBoardgame.find(params[:id])
    @user_boardgame.destroy
    authorize @user_boardgame
    redirect_to user_boardgames_path, notice: "#{@user_boardgame.boardgame.name} removed from collection."
  end

  private

  def user_boardgame_params
    params.require(:user_boardgame).permit(:boardgame_id)
  end
end

app/views/user_boardgames/_form.html.erb
<%= simple_form_for(user_boardgame) do |f| %>
  <%= f.association :boardgame, label: "boardgame", input_html: { data: {controller: 'select2'}  } %>
  <div class="form-actions d-flex justify-content-center">
    <%= f.button :submit, "add", class: "a_btn" %>
  </div>
<% end %>

app/views/user_boardgames/index.html.erb
<div class="px-4">
  <h1>my boardgames</h1>
  <%= link_to "add", new_user_boardgame_path, class:"a_btn" %>
  <% @user_boardgames.each do |user_boardgame| %>
    <%= link_to boardgame_path(user_boardgame.boardgame) do %>
      <div class="card-product">
        <%= cl_image_tag user_boardgame.boardgame.photo.key, width: 96 %>
        <div class="card-product-infos d-flex flex-column justify-content-between w-100">
            <h2><%= user_boardgame.boardgame.name %></h2>
              <%= link_to "remove", user_boardgame_path(user_boardgame), method: :delete, data: { confirm: 'Are you sure?' } %>
            <div class="boardgame-padding">
              <div class="d-flex justify-content-between">
                <p style="color: #A380BD"><i class="fa-solid fa-users"></i>
                  <% if user_boardgame.boardgame.min_players != user_boardgame.boardgame.max_players %>
                    <%= user_boardgame.boardgame.min_players %>-<%= user_boardgame.boardgame.max_players %>
                  <% else %>
                    <%= user_boardgame.boardgame.max_players %>
                  <% end %></p>
                <p style="color: #A380BD"><i class="fa-solid fa-star"></i> <%= user_boardgame.boardgame.rating.round(1) %>/10</p>
              </div>
              <div class="d-flex justify-content-between">
                <p style="color: #A380BD"><i class="fa-solid fa-clock"></i>
                  <% if user_boardgame.boardgame.min_time != user_boardgame.boardgame.max_time %>
                    <%= user_boardgame.boardgame.min_time %>-<%= user_boardgame.boardgame.max_time %>
                  <% else %>
                    <%= user_boardgame.boardgame.min_time %>
                  <% end %></p>
                <p style="color: #A380BD"><i class="fa-solid fa-gears"></i> <%= user_boardgame.boardgame.complexity.round(1) %>/5</p>
              </div>
            </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/user_boardgames/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-4 col-sm-offset-4">
      <div class="form-login-signup">
        <h1>add boardgame to my collection</h1>
        <%= render 'form', user_boardgame: @user_boardgame %>
      </div>
    </div>
  </div>
</div>