config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :meetings do
    resources :user_meetings, only: [:create]
  end
  resources :boardgames, only: [:index, :show]
  resources :user_meetings, only: [:destroy]
  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  get 'my_meetings', to: "meetings#my_meetings"
  get 'calendar', to: 'meetings#calendar'
  resources :user_boardgames, only: [:new, :create, :index, :destroy]
end

app/views/partials/_logo_landingpage.html.erb
<svg width="218" height="57" viewBox="0 0 218 57" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M103.268 56.665C102.451 56.665 101.764 56.3859 101.208 55.8276C100.688 55.3066 100.428 54.6366 100.428 53.8178V28.3604C100.466 25.4202 101.152 22.7777 102.488 20.4329C103.824 18.0881 105.643 16.2458 107.944 14.906C110.245 13.5289 112.842 12.8404 115.737 12.8404C118.669 12.8404 121.285 13.5289 123.586 14.906C125.887 16.2458 127.706 18.0881 129.042 20.4329C130.415 22.7777 131.102 25.4202 131.102 28.3604C131.102 31.3007 130.471 33.9432 129.209 36.2879C127.984 38.5955 126.296 40.4378 124.143 41.8149C121.991 43.1547 119.56 43.8247 116.851 43.8247C114.661 43.8247 112.638 43.3781 110.783 42.4848C108.964 41.5544 107.406 40.3075 106.107 38.7444V53.8178C106.107 54.6366 105.847 55.3066 105.327 55.8276C104.808 56.3859 104.121 56.665 103.268 56.665ZM115.737 38.8002C117.63 38.8002 119.318 38.3536 120.803 37.4603C122.287 36.5299 123.456 35.2831 124.31 33.7199C125.201 32.1195 125.646 30.333 125.646 28.3604C125.646 26.3506 125.201 24.5642 124.31 23.001C123.456 21.4006 122.287 20.1538 120.803 19.2605C119.318 18.3301 117.63 17.8648 115.737 17.8648C113.882 17.8648 112.193 18.3301 110.671 19.2605C109.187 20.1538 108.018 21.4006 107.164 23.001C106.311 24.5642 105.884 26.3506 105.884 28.3604C105.884 30.333 106.311 32.1195 107.164 33.7199C108.018 35.2831 109.187 36.5299 110.671 37.4603C112.193 38.3536 113.882 38.8002 115.737 38.8002Z" fill="#A380BD"/>
<path d="M146.807 43.6014C145.174 43.6014 143.727 43.1547 142.465 42.2615C141.203 41.3683 140.219 40.1587 139.514 38.6327C138.809 37.0695 138.457 35.2831 138.457 33.2733V2.79138C138.457 1.97258 138.716 1.30264 139.236 0.781586C139.756 0.260529 140.424 0 141.24 0C142.057 0 142.725 0.260529 143.244 0.781586C143.764 1.30264 144.023 1.97258 144.023 2.79138V33.2733C144.023 34.6503 144.283 35.7855 144.803 36.6787C145.322 37.572 145.99 38.0186 146.807 38.0186H148.199C148.941 38.0186 149.535 38.2791 149.98 38.8002C150.462 39.3213 150.704 39.9912 150.704 40.81C150.704 41.6288 150.351 42.2987 149.646 42.8198C148.941 43.3408 148.032 43.6014 146.918 43.6014H146.807Z" fill="#A380BD"/>
<path d="M167.267 43.8247C164.557 43.8247 162.127 43.1547 159.974 41.8149C157.822 40.4378 156.114 38.5955 154.853 36.2879C153.628 33.9432 153.016 31.3007 153.016 28.3604C153.016 25.4202 153.684 22.7777 155.02 20.4329C156.393 18.0881 158.23 16.2458 160.531 14.906C162.869 13.5289 165.485 12.8404 168.38 12.8404C171.275 12.8404 173.872 13.5289 176.173 14.906C178.474 16.2458 180.293 18.0881 181.629 20.4329C183.002 22.7777 183.689 25.4202 183.689 28.3604H181.518C181.518 31.3007 180.887 33.9432 179.625 36.2879C178.4 38.5955 176.712 40.4378 174.559 41.8149C172.407 43.1547 169.976 43.8247 167.267 43.8247ZM168.38 38.8002C170.273 38.8002 171.961 38.3536 173.446 37.4603C174.93 36.5299 176.099 35.2831 176.953 33.7199C177.806 32.1195 178.233 30.333 178.233 28.3604C178.233 26.3506 177.806 24.5642 176.953 23.001C176.099 21.4006 174.93 20.1538 173.446 19.2605C171.961 18.3301 170.273 17.8648 168.38 17.8648C166.524 17.8648 164.836 18.3301 163.314 19.2605C161.83 20.1538 160.642 21.4006 159.751 23.001C158.898 24.5642 158.471 26.3506 158.471 28.3604C158.471 30.333 158.898 32.1195 159.751 33.7199C160.642 35.2831 161.83 36.5299 163.314 37.4603C164.836 38.3536 166.524 38.8002 168.38 38.8002ZM180.85 43.6572C180.033 43.6572 179.347 43.3967 178.79 42.8756C178.27 42.3173 178.01 41.6288 178.01 40.81V32.2684L179.068 26.3506L183.689 28.3604V40.81C183.689 41.6288 183.41 42.3173 182.854 42.8756C182.334 43.3967 181.666 43.6572 180.85 43.6572Z" fill="#A380BD"/>
<path d="M197.595 57C197.224 57 196.778 56.8883 196.259 56.665C194.626 55.9207 194.18 54.7483 194.923 53.1479L211.901 14.6827C212.644 13.1195 213.813 12.6729 215.408 13.3428C217.079 14.0499 217.542 15.2223 216.8 16.8599L199.766 55.2693C199.32 56.4231 198.597 57 197.595 57ZM204.164 42.3732C203.458 42.6709 202.79 42.7081 202.16 42.4848C201.566 42.2243 201.083 41.7404 200.712 41.0333L187.964 16.7483C187.593 16.0411 187.537 15.3712 187.797 14.7385C188.094 14.0686 188.595 13.5847 189.3 13.287C190.005 12.9892 190.673 12.9706 191.304 13.2311C191.935 13.4545 192.418 13.9197 192.752 14.6268L204.943 38.9118C205.314 39.619 205.444 40.3075 205.333 40.9775C205.258 41.6102 204.869 42.0754 204.164 42.3732Z" fill="#A380BD"/>
<path d="M2.30916 13.5713H6.88949L14.549 36.0462L22.1893 13.5713H26.7889L16.3773 43.4284H12.7015L2.30916 13.5713ZM-0.000244141 13.5713H4.48385L5.29215 34.2211V43.4284H-0.000244141V13.5713ZM24.5949 13.5713H29.0983V43.4284H23.8059V34.2211L24.5949 13.5713Z" fill="#A380BD"/>
<path d="M59.714 38.9991V43.4284H44.8184V38.9991H59.714ZM46.435 13.5713V43.4284H41.1426V13.5713H46.435ZM57.7703 25.8956V30.2224H44.8184V25.8956H57.7703ZM59.6563 13.5713V18.0212H44.8184V13.5713H59.6563Z" fill="#A380BD"/>
<path d="M89.5714 38.9991V43.4284H74.6757V38.9991H89.5714ZM76.2923 13.5713V43.4284H70.9999V13.5713H76.2923ZM87.6277 25.8956V30.2224H74.6757V25.8956H87.6277ZM89.5137 13.5713V18.0212H74.6757V13.5713H89.5137Z" fill="#A380BD"/>
</svg>

app/views/partials/_navbarbottom.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-bottom m-height-navbar border-navbar px-2" >
  <div class="container-fluid align-items-start">
    <%= link_to(meetings_path, class:'nav-link') do %>
      <% if params[:controller] == 'meetings' && params[:action] == 'index' %>
        <%= render 'shared/house_filled' %>
      <% else %>
        <%= render 'shared/house' %>
      <% end %>
    <% end %>
    <%= link_to(calendar_path , class:'nav-link') do %>
      <% if params[:controller] == 'meetings' && params[:action] == 'calendar' %>
        <i class="fa-solid fa-calendar calendar_btn"></i>
      <% else %>
        <i class="fa-regular fa-calendar calendar_btn"></i>
      <% end %>
    <% end %>
    <%= link_to(new_meeting_path, class:'nav-link plus_btn height1 material') do %>
      <i class="fas fa-plus"></i>
    <% end %>
    <%= link_to(chatrooms_path, class:'nav-link messages_btn') do %>
      <% if params[:controller] == 'chatrooms' %>
        <i class="fa-solid fa-message"></i>
      <% else %>
        <i class="fa-regular fa-message"></i>
      <% end %>
    <% end %>

    <%= link_to(profile_path(current_user.profile), class:'nav-link') do %>
       <% if params[:controller] == 'profiles' %>
        <i class="fa-solid fa-user avatar_btn "></i>
       <% else %>
         <i class="fa-regular fa-user avatar_btn "></i>
       <% end %>
    <% end %>
  </div>
</div>