config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :meetings do
    resources :user_meetings, only: [:create]
  end
  resources :boardgames, only: [:index, :show]
  resources :user_meetings, only: [:destroy]
  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  get 'my_meetings', to: "meetings#my_meetings"
  get 'calendar', to: 'meetings#calendar'
  resources :user_boardgames, only: [:new, :create, :index, :destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_house.html.erb
<svg width="30" height="25" viewBox="0 0 30 25" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M29.2564 13.7846L22.463 7.03459V1.33934C22.463 0.599697 21.8596 5.58001e-05 21.1152 5.58001e-05C20.3709 5.58001e-05 19.7675 0.599697 19.7675 1.33934V4.35621L15.778 0.392198C15.2518 -0.130747 14.3984 -0.130747 13.8721 0.392287L0.394764 13.7847C-0.131588 14.3076 -0.131588 15.1556 0.394764 15.6787C0.65794 15.9402 1.00279 16.071 1.34773 16.071C1.69267 16.071 2.03762 15.9402 2.3007 15.6787L4.49264 13.5007V23.6607C4.49264 24.4004 5.09608 25 5.84042 25H12.13H17.5212H23.8108C24.5551 25 25.1586 24.4004 25.1586 23.6607V13.5008L27.3504 15.6788C27.8767 16.2017 28.7301 16.2016 29.2564 15.6787C29.7828 15.1556 29.7827 14.3076 29.2564 13.7846ZM13.4778 22.3214V16.9643H16.1734V22.3214H13.4778ZM22.463 22.3214H18.8689V15.625C18.8689 14.8854 18.2655 14.2857 17.5212 14.2857H12.13C11.3857 14.2857 10.7823 14.8854 10.7823 15.625V22.3214H7.1882V10.8221L14.8252 3.23335L22.463 10.8225V22.3214Z" fill="#A380BD"/>
</svg>

app/views/shared/_house_filled.html.erb
<svg width="30" height="25" viewBox="0 0 30 25" fill="none" xmlns="http://www.w3.org/2000/svg" >
  <path d="M22.463 7.03459L29.2564 13.7846C29.7827 14.3076 29.7828 15.1556 29.2564 15.6787C28.7301 16.2016 27.8767 16.2017 27.3504 15.6788L25.1586 13.5008V23.6607C25.1586 24.4004 24.5551 25 23.8108 25H17.5212H12.13H5.84042C5.09608 25 4.49264 24.4004 4.49264 23.6607V13.5007L2.3007 15.6787C2.03762 15.9402 1.69267 16.071 1.34773 16.071C1.00279 16.071 0.65794 15.9402 0.394764 15.6787C-0.131588 15.1556 -0.131588 14.3076 0.394764 13.7847L13.8721 0.392287C14.3984 -0.130747 15.2518 -0.130747 15.778 0.392198L19.7675 4.35621V1.33934C19.7675 0.599697 20.3709 5.57849e-05 21.1152 5.57849e-05C21.8596 5.57849e-05 22.463 0.599697 22.463 1.33934V7.03459Z" fill="#A380BD"/>
</svg>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_magnifyingglass.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M500.3 443.7l-119.7-119.7c27.22-40.41 40.65-90.9 33.46-144.7C401.8 87.79 326.8 13.32 235.2 1.723C99.01-15.51-15.51 99.01 1.724 235.2c11.6 91.64 86.08 166.7 177.6 178.9c53.8 7.189 104.3-6.236 144.7-33.46l119.7 119.7c15.62 15.62 40.95 15.62 56.57 0C515.9 484.7 515.9 459.3 500.3 443.7zM79.1 208c0-70.58 57.42-128 128-128s128 57.42 128 128c0 70.58-57.42 128-128 128S79.1 278.6 79.1 208z"/></svg>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-top px-3" data-controller="dropdown">
  <div class="back-arrow">
    <% if user_signed_in? %>
      <%= link_to :back do %>
        <h1><</h1>
      <% end %>
    <% end %>
  </div>
  <div class="navbar-brand">
    <%= link_to meetings_path do %>
      <%= render 'shared/meeple_svg' %>
    <% end %>
  </div>
  <div class="dropdown">
    <a class="btn text-light" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
      <%= render 'shared/navbar_toggler' %>
    </a>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <% if user_signed_in? %>
          <%= link_to "my meetings", my_meetings_path, class: "dropdown-item" %>
          <%= link_to "my boardgames", user_boardgames_path, class: "dropdown-item" %>
          <%= link_to "all boardgames", boardgames_path, class: "dropdown-item" %>
          <%= link_to "log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% else %>
          <%= link_to "log in", new_user_session_path, class: "dropdown-item" %>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_toggler.html.erb
<svg width="21" height="18" viewBox="0 0 21 18" fill="none" xmlns="http://www.w3.org/2000/svg" data-action="click->dropdown#dropdownMenu" >
  <path  d="M0 1.5C0 0.671719 0.671719 0 1.5 0H19.5C20.3297 0 21 0.671719 21 1.5C21 2.32969 20.3297 3 19.5 3H1.5C0.671719 3 0 2.32969 0 1.5ZM0 9C0 8.17031 0.671719 7.5 1.5 7.5H19.5C20.3297 7.5 21 8.17031 21 9C21 9.82969 20.3297 10.5 19.5 10.5H1.5C0.671719 10.5 0 9.82969 0 9ZM19.5 18H1.5C0.671719 18 0 17.3297 0 16.5C0 15.6703 0.671719 15 1.5 15H19.5C20.3297 15 21 15.6703 21 16.5C21 17.3297 20.3297 18 19.5 18Z" fill="#6e6d6d"/>
</svg>